version: "3.8"
services:
    mongodb:
        image : mongo
        container_name: xai-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: XAI
            MONGO_INITDB_ROOT_PASSWORD: InfoSupportXAI
            MONGO_INITDB_DATABASE: XAI
        volumes:
            - C:\XAII\data\mongo\:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - 27017:27017
        restart: always
        